common:
 invite_only: true
 minimum_goal: 0

development:
 host: tax.dev
 analytics_key:
 fb_app_id: 53634552952

staging:
 host: awesometax.awesomefoundation.org
 analytics_key:
 fb_app_id: 53634552952

production:
 host: awesometax.awesomefoundation.org
 analytics_key: UA-15180627-6
 fb_app_id: 375385414659