local: &local
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: 
  host: localhost
  encoding: utf8


lime: &lime
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: rails
  password: huju5Azafu
  host: lime_private



development:
  <<: *local
  database: lovetax_local
  
test:
  <<: *local
  database: lovetax_test

staging:
  <<: *lime
  database: lovetax_stage

production:
  <<: *lime
  database: lovetax_prod
