development:
  environment: "sandbox"
  username: "shoppy_1274735670_biz_api1.gmail.com"
  password: "1274735677"
  signature: "AFcWxV21C7fd0v3bYYYRCpSSRl31A.N0-dzJEtTKLRY.kUoeSRyAan5I"
  application_id: "APP-80W284485P519543T"

test:
  environment: "sandbox"
  username: "shoppy_1274735670_biz_api1.gmail.com"
  password: "1274735677"
  signature: "AFcWxV21C7fd0v3bYYYRCpSSRl31A.N0-dzJEtTKLRY.kUoeSRyAan5I"
  application_id: "APP-80W284485P519543T"

staging:
  environment: "sandbox"
  username: "shoppy_1274735670_biz_api1.gmail.com"
  password: "1274735677"
  signature: "AFcWxV21C7fd0v3bYYYRCpSSRl31A.N0-dzJEtTKLRY.kUoeSRyAan5I"
  application_id: "APP-80W284485P519543T"

production:
  environment: "sandbox"
  username: ENV['PAYPAL_USERNAME']
  password: ENV['PAYPAL_PASSWORD']
  signature: ENV['PAYPAL_SIGNATURE']
  application_id: ENV['PAYPAL_APP_ID']